### ISSUE TITLE
sequence same length error.

### ISSUE THREAD

**Issue by Youpu-Chen** [mjobin/Imputor#1]
Hi there. I've accounted some issues, could you give me a hint?
```
Traceback (most recent call last):
  File "/share1/home/chenhongpu/opt/biosoft/Imputor/imputor.py", line 1468, in <module>
    indata = InData(infile, reffile)
  File "/share1/home/chenhongpu/opt/biosoft/Imputor/imputor.py", line 68, in __init__
    self.load_input_data()
  File "/share1/home/chenhongpu/opt/biosoft/Imputor/imputor.py", line 94, in load_input_data
    self.seq_from_variants(raw_data)
  File "/share1/home/chenhongpu/opt/biosoft/Imputor/imputor.py", line 405, in seq_from_variants
    self.sequence.append(SeqRecord(Seq(''.join(genotype_sequence[geno])), name=geno, id=geno))
  File "/home/chenhongpu/opt/biosoft/mambaforge/envs/py_2/lib/python2.7/site-packages/Bio/Align/__init__.py", line 534, in append
    self._append(record, self.get_alignment_length())
  File "/home/chenhongpu/opt/biosoft/mambaforge/envs/py_2/lib/python2.7/site-packages/Bio/Align/__init__.py", line 550, in _append
    raise ValueError("Sequences must all be the same length")
ValueError: Sequences must all be the same length
```

**Comment by mjobin** [comment]
Ho Youpu, sorry to be slow. I’m not able to see your iunput data, but the sequences input into the program but all be equally long. If you are using for exmaplke a FASTA file, check that all the sequences in that file are the same length.

Matt
